run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gosimple

linters-settings:
  goimports:
    local-prefixes: github.com/upbound/interview-reconciler

issues:
  exclude-rules:
    - path: zz_generated.*\.go
      linters:
        - goimports
        - gofmt
    - path: _test\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
